### ISSUE TITLE
Error connecting to SQL2014 -> ConnectionError: Connection is closed.

### ISSUE THREAD

**Issue by stephan-simondshealth-com-au** [jsreport/jsreport-mssql-store#1]
On Win2012 R2 Server

Using this config:

```
"connectionString": { 
    "name": "mssql",
    "user": "svc_user_dev",
    "password": "abcdef",
    "server": "locallhost\\SQLEXPRESS",
    "database": "MyAwesomeApp-Dev"
},
```

I'm getting this error

2016-07-19T11:51:41.953Z - error: Error occured during reporter init ConnectionE
rror: Connection is closed.
    at D:\Deploy\dev\NodeJS\node_modules\mssql\lib\main.js:1519:17
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
From previous event:
    at Array.reduce (native)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
ConnectionError: Connection is closed.
    at D:\Deploy\dev\NodeJS\node_modules\mssql\lib\main.js:1519:17
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
From previous event:
    at Array.reduce (native)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)

Any ideas?

**Comment by pofider** [comment]
Please let me know which version of jsreport you have

**Comment by pofider** [comment]
Also please make sure your TCP/IP protocol is enabled in the SQL Server Configuration Manager

**Comment by pofider** [comment]
Maybe you can also change `locallhost` with your computer name, if it doesn't help. 

I tried it on my windows and I'm able to connect, however I see some issues with the latest version UI which I'll quickly fix

**Comment by stephan-simondshealth-com-au** [comment]
Hi Thanks for the prompt reply. I'm no AU timezone, so enjoying my morning coffee now. Hence my delayed response.

Here is my config:
- Clean install, the latest version. (See screenshot)
  ![image](https://cloud.githubusercontent.com/assets/15353977/16966753/58bbd816-4e49-11e6-823f-73df4ba5505c.png)
- Node Version: v6.2.1
- TCP/IP is enabled.     (Manually enabled after default SQL Express install using chocolatey)
- Tried localhost, (local), 127.0.0.1, MACHINENAME, etc.   (Multiple slashes, single slashes)
- I can connect using the same username / pwd (copy-pasted) using "SQL Server Management Studio"
- I tried increasing the tedious version to 1.14.0 as their latest version (7.4 ??) includes SQL2014 support. But that didn't help either
- I changed the port to 5488 to make sure jsreport was using the config I was editing.

Questions:
- Does the database need to exist already?  (I tried both btw)

Thanks for your help !

**Comment by pofider** [comment]
And I'm in Europe, so another timezone delay :)
- Do you have sql server browser service running?
- Maybe try to fix the typo locallhost  => localhost in your config
- Db needs to exist
- try to add to the connection string `options: {  encrypt: true }`
- Check the mssql package issues - https://github.com/patriksimek/node-mssql/issues/138

**Comment by stephan-simondshealth-com-au** [comment]
Hi Jan,

Yeah, it's a good excuse isn't it :-) :-)

Good news, its working now.
For future reference:

It was the combination of:
- The "SQL Server Browser" which wasn't running and
- encrypt option wasn't set.

I did try both, but not at the same time until now.
Also, the "encrypt" option kept being mentioned for Azure SQL, so wasn't sure whether I needed it.

Awesome work,
Thanks for the quick replies!

As a token of my appreciation, I'm happy to send you a draft for updating the help pages to include these tips. I can also take the hint if you decide to thankfully decline or not to add them :-) :-)

Cheers!
