### ISSUE TITLE
[ConnectionError: Connection is closed.] while insert data through stored procedure

### ISSUE THREAD

**Issue by farell** [jsreport/jsreport-mssql-store#2]
I insert successive data through the snippet  bellow,

```
sql.connect(dataconfig).then(function() {
               // Stored Procedure
        new sql.Request()
        .input('SensorID', sql.VarChar(20),"'"+msg.SensorId+"'")
        .input('StampTime', sql.VarChar(50), "'"+msg.Time+"'")
        .input('VauleType', sql.VarChar(50), "'"+msg.DataType+"'")
        .input('Values', sql.VarChar(50),"'"+ msg.Value.toString()+"'")
          .output('ret', sql.VarChar(50))
        .execute('INSERT_PROC').then(function(recordsets) {
            logger.warn('inserted item:'+JSON.stringify(msg));
        }).catch(function(err) {
            logger.warn(err);
        });
      }).catch(function(err) {
        console.log(`sql connect err:${err}`);
        logger.fatal(err);
      });
```

some of the insertion succeeded,but some didn't.
I got the following error when it got error:

{ [ConnectionError: Connection is closed.]
     name: 'ConnectionError',
     message: 'Connection is closed.',
     code: 'ECONNCLOSED' }
at D:\kmlc\DataStore\node_modules\mssql\lib\main.js:1663:17
       at doNTCallback0 (node.js:428:9)
       at process._tickCallback (node.js:357:13)

I must have done something wrong,can somebody help?Thanks

**Comment by pofider** [comment]
Didn't you posted this to the wrong repository? 

Maybe you are rather searching for [mssql](https://github.com/patriksimek/node-mssql) repository.

**Comment by farell** [comment]
god......
