### ISSUE TITLE
Deprecated warnings around tedious.JS dependency

### ISSUE THREAD

**Issue by ChrisNeff** [jsreport/jsreport-mssql-store#4]
See the same issues as listed here:
https://github.com/tediousjs/node-mssql/issues/651

**Comment by pofider** [comment]
Yes, this was rather a bug in mssql package.
I updated the version to the vnext and the warnings are gone.

**Comment by ChrisNeff** [comment]
Awesome!  We very much appreciate your efforts and turnaround on this issue.
