### ISSUE TITLE
Azure MSSQL Store

### ISSUE THREAD

**Issue by Css-IanM** [jsreport/jsreport-mssql-store#5]
I'm having trouble tracking down the environment variables to set to enable an mssql store on Azure. Is azure blob storage the only azure feature available?

I've probably missed something simple. Each variable is a direct correlation to configuration options with nesting depicted with `_`  and substituting kabob casing with camel casing correct?
I've set 
`store_provder = mssql`
`extensions_mssqlStore_uri = "my connection string"`
I've also tried...
`extensions_mssql-store_uri = "my connection string"`
is there some additional documentation or something i'm missing or misunderstanding?

Edit: Just to pre-emptively confirm I am using the full variation of the docker image that includes the extensions.

**Comment by pofider** [comment]
The example configuration for ms sql store provider is described here
https://github.com/jsreport/jsreport-mssql-store

```js
"store": {
	"provider": "mssql"
},
"extensions": {
	"mssql-store": {
		"uri": "Server=tcp:jsreport.database.windows.net,1433;Initial Catalog=jsreport;Persist Security Info=False;User ID=myuser;Password=password;MultipleActiveResultSets=False;Encrypt=True;"
	}
}
```

This can be transformed into env variables this way
https://jsreport.net/learn/configuration
> If you want to use environment variable for configuring a complex object you should separate the nested path in the key using _
> extensions that has a name with a hyphen in it (like html-to-xlsx for example) also supports receiving configuration with the name in camel case

So you should use variables
`store_provider=mssql`  // you had typo there
`extensions_mssqlStore_uri=....`

Here you can find also example how to use azure blob storage
https://jsreport.net/blog/render-reports-using-azure-app-service

**Comment by Css-IanM** [comment]
The typo was just here on GitHub :) derp!
The container appears to be taking the variables correctly after some additional digging in the logs.
The issue was with the connection string specifying a Timeout.
